### ISSUE TITLE
Occasional issue with feed-reader meta inspector

### ISSUE THREAD

**Issue by cjwiseman11** [cjwiseman11/feedify-nodejs#17]

**Comment by cjwiseman11** [comment]
This issue seems to be fixed since error handling was added

**Comment by cjwiseman11** [comment]
It seems like this issue is still present, but quite rare. 

Error from logs (can't get full logs currently):


0|index    | 2017-10-24 15:45 +00:00:
0|index    | (sharp:14137): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
0|index    | 2017-10-24 15:45 +00:00:
0|index    | (sharp:14137): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
0|index    | 2017-10-24 16:00 +00:00: Error: undefined is not a valid uri or options object.
0|index    |     at request (/var/www/feedify.xyz/html/feedify-nodejs/node_modules/request/index.js:44:11)
0|index    |     at MetaInspector.<anonymous> (/var/www/feedify.xyz/html/feedify-nodejs/scripts/feed-reader.js:111:5)
0|index    |     at emitNone (events.js:86:13)
0|index    |     at MetaInspector.emit (events.js:185:7)
0|index    |     at Request._callback (/var/www/feedify.xyz/html/feedify-nodejs/node_modules/node-metainspector/index.js:312:10)
0|index    |     at Request.self.callback (/var/www/feedify.xyz/html/feedify-nodejs/node_modules/node-metainspector/node_modules/request/request.js:197:22)
0|index    |     at emitTwo (events.js:106:13)
0|index    |     at Request.emit (events.js:191:7)
0|index    |     at Request.<anonymous> (/var/www/feedify.xyz/html/feedify-nodejs/node_modules/node-metainspector/node_modules/request/request.js:1050:14)
0|index    |     at emitOne (events.js:101:20)
